import AppHeader from '@/components/header'
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AppHeader />
        {children}
        <footer class="bg-gray-800 p-4">
        <div class="container mx-auto text-center">
          <p>&copy; 2023 Day2Movies. All rights reserved.</p>
        </div>
      </footer>
      </body>
    </html>
  )
}
